version: '3.8'

services:
  starknet-devnet:
    image: shardlabs/starknet-devnet:latest
    ports:
      - "5050:5050"
    command: --seed 42 --accounts 3
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/is_alive"]
      interval: 5s
      timeout: 5s
      retries: 5

  contract-deployer:
    build:
      context: .
      dockerfile: Dockerfile.deployer.fixed
    volumes:
      - ./contract-addresses:/app/contract-addresses
      - ./target:/app/target
    environment:
      - STARKNET_NETWORK=devnet
      - STARKNET_RPC_URL=http://starknet-devnet:5050
    depends_on:
      starknet-devnet:
        condition: service_healthy
