version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    command: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app/frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_STARKNET_NETWORK=sepolia
      - NEXT_PUBLIC_PROVIDER_URL=https://starknet-sepolia.infura.io/v3/0d3e154c01d243f3be0e42d3b861bc9e
