version: '3'
services:
  # Starknet Devnet for local development
  starknet-devnet:
    image: starknetfoundation/starknet-dev:latest
    ports:
      - "5050:5050"
    command: starknet-devnet --host 0.0.0.0 --port 5050 --seed 42 --accounts 10 --lite-mode
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050/is_alive"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
    networks:
      - starknet-network
  # Contract deployment service using TypeScript
  contract-deployer:
    build:
      context: .
      dockerfile: Dockerfile.deployer
    volumes:
      - ./deployments:/app/deployments
      # Removed the target volume mount that was overriding built artifacts
    depends_on:
      starknet-devnet:
        condition: service_healthy
    environment:
      - STARKNET_DEVNET_URL=http://starknet-devnet:5050
    networks:
      - starknet-network
  # Frontend application
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.unified
    command: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./deployments:/app/deployments:ro
      # Removed the target volume mount that was overriding built artifacts
    environment:
      - NEXT_PUBLIC_STARKNET_NETWORK=devnet
      - NEXT_PUBLIC_PROVIDER_URL=http://starknet-devnet:5050
    depends_on:
      contract-deployer:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - starknet-network
networks:
  starknet-network:
    driver: bridge
