[package]
name = "prophecy_sunya"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.11.4"

[dependencies]
starknet = ">=2.11.0"

[cairo]
sierra-replace-ids = true

[tool.plugin]
starknet = { version = ">=2.11.0" }

# Main contract target configuration
[[target.starknet-contract]]
sierra = true
casm = true

# Explicit contract targets
[[target.starknet-contract]]
name = "prophecy_sunya_prediction"
path = "src/prediction_contract.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "prophecy_sunya_nft"
path = "src/nft_contract.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "prophecy_sunya_gas_tank"
path = "src/gas_tank_contract.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "prophecy_sunya_oracle"
path = "src/oracle_contract.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "prophecy_sunya_governance"
path = "src/governance_contract.cairo"
sierra = true
casm = true

[[target.starknet-contract]]
name = "prophecy_sunya_bridge"
path = "src/bridge_contract.cairo"
sierra = true
casm = true
