[package]
name = "prediction"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.4.0"

[dependencies]
starknet = ">=2.4.0"
shared = { path = "../shared" }

[[target.starknet-contract]]
sierra = true
casm = true
