[package]
name = "gas_tank"
version = "0.1.0"
edition = "2023_10"
cairo-version = "2.11.4"

[dependencies]
starknet = ">=2.4.0"
shared = { path = "../shared" }

[[target.starknet-contract]]
sierra = true
casm = true
